name: ood-rl-env
channels:
  - conda-forge
  - defaults
  - nvidia
dependencies:
  - python=3.7
  - nvidia::cudatoolkit=11.3
  - pytorch::pytorch
  - stable-baselines3
  - gym
  - wandb
  - hydra-core
  - seaborn
  - pip:
    - mujoco-py
    - sb3-contrib>=1.3.0
    - optuna
    - tensorboard
    - pyglet
    - sklearn
