name: ood-rl-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - stable-baselines3
  - gym
  - wandb
  - hydra-core
  - seaborn
  - pip:
    - mujoco-py
    - sb3-contrib>=1.3.0
    - optuna
    - tensorboard
