model: PPO
env: CartPole-v1
total_timesteps: 100000
n_frames_stack: 4
image_input: True

ood_config:
  use: False
  prob: 0.05
  type: random
  random_std: 0.5

stable_baselines:
  verbosity: 1
  policy_class: CnnPolicy

wandb:
  entity: nyu_drl
  project: test-project
  key: 1b2711d130518c5e80d47a6341cfaf2e4b9f5903
