model: PPO
env: CartPole-v1
total_timesteps: 100000

stable_baselines:
  verbosity: 1
  policy_class: MlpPolicy

wandb:
  entity: nyu_drl
  project: test-project
  key: 1b2711d130518c5e80d47a6341cfaf2e4b9f5903
